version: '2'

services:
  web:
    extends:
      file: common.yml
      service: web

  mongo:
    image: mongo:2
    command: mongod --smallfiles
#     volumes:
#       - mongo-data:/data/db

# volumes:
#   mongo-data:
#     driver: local
