version: '2'

services:

  web:
    build:
      context: web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis

  worker:
    build:
      context: worker
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - TIMEOUT=10000

  redis:
    image: redis
